home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

owner_user:
    resource: "@OwnerUserBundle/Controller/"
    type:     annotation
    prefix:   /

redeemar_user:
    resource: "@RedeemarUserBundle/Controller/"
    type:     annotation
    prefix:   /

system_user:
    resource: "@SystemUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
