AppBundle\Entity\Category:
    type: entity
    table: category
    indexes:
        idx_name:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 150
            fixed: false
    lifecycleCallbacks: {  }
