AppBundle\Entity\Company:
    type: entity
    table: company
    indexes:
        fk_user_id:
            columns:
                - user_id
        fk_category_id:
            columns:
                - category_id
        fk_logo_id:
            columns:
                - logo_id
    uniqueConstraints:
        uidx_name:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        website:
            type: string
            nullable: false
            length: 100
            fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            fixed: false
        address:
            type: string
            nullable: false
            length: 255
            fixed: false
        video:
            type: text
            nullable: false
            length: 65535
            fixed: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        logo:
            targetEntity: Logo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                logo_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
