AppBundle\Entity\Invoice:
    type: entity
    table: invoice
    indexes:
        fk_user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        referenceNumber:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: reference_number
        invoiceDate:
            type: datetime
            nullable: false
            column: invoice_date
        statusId:
            type: integer
            nullable: false
            unsigned: false
            column: status_id
        totalAmount:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            column: total_amount
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
