AppBundle\Entity\Location:
    type: entity
    table: location
    indexes:
        fk_company_id:
            columns:
                - company_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        address:
            type: string
            nullable: false
            length: 100
            fixed: false
        phone:
            type: string
            nullable: false
            length: 25
            fixed: false
        contact:
            type: string
            nullable: false
            length: 100
            fixed: false
        active:
            type: boolean
            nullable: false
        longitude:
            type: float
            nullable: false
            precision: 10
            scale: 0
        latitude:
            type: float
            nullable: false
            precision: 10
            scale: 0
        created:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
        modified:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
    manyToOne:
        company:
            targetEntity: Company
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
