AppBundle\Entity\Logo:
    type: entity
    table: logo
    uniqueConstraints:
        uidx_company_name:
            columns:
                - company_name
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        companyName:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: company_name
        path:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
