AppBundle\Entity\Offer:
    type: entity
    table: offer
    indexes:
        idx_campaign_name:
            columns:
                - campaign_name
        idx_start_date:
            columns:
                - start_date
        idx_end_date:
            columns:
                - end_date
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        campaignName:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: campaign_name
        startDate:
            type: datetime
            nullable: false
            column: start_date
        endDate:
            type: datetime
            nullable: false
            column: end_date
        imagePath:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: image_path
        prepay:
            type: boolean
            nullable: false
        payOnValidate:
            type: boolean
            nullable: false
            column: pay_on_validate
        fixedAmount:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            column: fixed_amount
        percentage:
            type: smallint
            nullable: false
            unsigned: false
        redeemarsForValidation:
            type: integer
            nullable: false
            unsigned: false
            comment: 'his is how many Redeemars will be available for validation'
            column: redeemars_for_validation
        redeemarPrice:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            comment: 'this is the Price of each Redeemar, the mínimum is $50.'
            column: redeemar_price
        redeemarsUsed:
            type: integer
            nullable: false
            unsigned: false
            comment: 'number of redeemars that the owner wants to use in this offer.'
            column: redeemars_used
    lifecycleCallbacks: {  }
