AppBundle\Entity\Role:
    type: entity
    table: role
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            fixed: false
    lifecycleCallbacks: {  }
