AppBundle\Entity\User:
    type: entity
    table: user
    indexes:
        idx_active:
            columns:
                - active
        fk_role_id:
            columns:
                - role_id
    uniqueConstraints:
        uidx_username:
            columns:
                - username
        uidx_email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 60
            fixed: false
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        registered:
            type: datetime
            nullable: false
        active:
            type: boolean
            nullable: false
        created:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
        modified:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
    manyToOne:
        role:
            targetEntity: Role
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
