AppBundle\Entity\ValidatorUser:
    type: entity
    table: validator_user
    indexes:
        fk_company_id:
            columns:
                - company_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
        phone:
            type: string
            nullable: false
            length: 50
            fixed: false
        ipad:
            type: string
            nullable: false
            length: 50
            fixed: false
        charge:
            type: string
            nullable: false
            length: 100
            fixed: false
        active:
            type: boolean
            nullable: false
    manyToOne:
        company:
            targetEntity: Company
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
