services:
      app.menu_builder:
        class: OwnerUserBundle\DependencyInjection\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
          - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu
          - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar } # Named "sidebar" this time

      app.datatable.offer:
          class: OwnerUserBundle\Datatables\OfferDatatable
          tags:
              - { name: sg.datatable.view }
      app.datatable.dashboard:
          class: OwnerUserBundle\Datatables\DashboardDatatable
          tags:
              - { name: sg.datatable.view }              
